export const SCHEDULER_SCHEMAS = {
  jobs: {
    type: 'object',
    required: ['name', 'payload_message', 'run_timeout_ms'], // origin also required for non-child jobs
    fields: {
      name: { type: 'string', maxLength: 200 },
      enabled: { type: 'boolean', default: true },
      schedule_cron: { type: 'string', requiredFor: 'root jobs' },
      schedule_tz: { type: 'string', default: 'UTC' },
      session_target: { type: 'string', enum: ['main', 'isolated', 'shell'], default: 'isolated' },
      payload_kind: { type: 'string', enum: ['systemEvent', 'agentTurn', 'shellCommand'] },
      payload_message: { type: 'string', maxLength: 100000 },
      payload_model: { type: 'string', nullable: true },
      payload_thinking: { type: 'string', nullable: true },
      payload_timeout_seconds: { type: 'integer', min: 1, default: 120 },
      execution_intent: { type: 'string', enum: ['execute', 'plan'], default: 'execute' },
      execution_read_only: { type: 'boolean', default: false },
      overlap_policy: { type: 'string', enum: ['skip', 'allow', 'queue'], default: 'skip' },
      run_timeout_ms: { type: 'integer', min: 1, required: true, description: 'Required: max ms a run may execute before timeout (no default — caller must be explicit)' },
      max_queued_dispatches: { type: 'integer', min: 1, default: 25 },
      max_pending_approvals: { type: 'integer', min: 1, default: 10 },
      max_trigger_fanout: { type: 'integer', min: 1, default: 25 },
      delivery_mode: { type: 'string', enum: ['announce', 'announce-always', 'none'], default: 'announce' },
      delivery_channel: { type: 'string', nullable: true },
      delivery_to: { type: 'string', nullable: true },
      parent_id: { type: 'string', nullable: true },
      trigger_on: { type: 'string', enum: ['success', 'failure', 'complete'], nullable: true },
      trigger_delay_s: { type: 'integer', min: 0, default: 0 },
      trigger_condition: { type: 'string', nullable: true, examples: ['contains:ALERT', 'regex:ERROR.*critical'] },
      max_retries: { type: 'integer', min: 0, default: 0 },
      payload_scope: { type: 'string', enum: ['own', 'global'], default: 'own' },
      resource_pool: { type: 'string', nullable: true },
      delivery_guarantee: { type: 'string', enum: ['at-most-once', 'at-least-once'], default: 'at-most-once' },
      job_class: { type: 'string', enum: ['standard', 'pre_compaction_flush'], default: 'standard' },
      approval_required: { type: 'boolean', default: false },
      approval_timeout_s: { type: 'integer', min: 1, default: 3600 },
      approval_auto: { type: 'string', enum: ['approve', 'reject'], default: 'reject' },
      context_retrieval: { type: 'string', enum: ['none', 'recent', 'hybrid'], default: 'none' },
      context_retrieval_limit: { type: 'integer', min: 1, default: 5 },
      output_store_limit_bytes: { type: 'integer', min: 128, default: 65536 },
      output_excerpt_limit_bytes: { type: 'integer', min: 64, default: 2000 },
      output_summary_limit_bytes: { type: 'integer', min: 64, default: 5000 },
      output_offload_threshold_bytes: { type: 'integer', min: 128, default: 65536 },
      preferred_session_key: { type: 'string', nullable: true },
      auth_profile: { type: 'string', nullable: true, description: 'Auth profile override: null=default, "inherit"=main session profile, or "provider:label"' },
      delivery_opt_out_reason: { type: 'string', nullable: true, maxLength: 256 },
      delete_after_run: { type: 'boolean', default: false },
      run_now: { type: 'boolean', default: false, note: 'create-time convenience flag' },

      // v0.2 Identity
      identity_principal: { type: 'string', nullable: true },
      identity_run_as: { type: 'string', nullable: true },
      identity_attestation: { type: 'string', nullable: true },
      identity_ref: { type: 'string', nullable: true },
      identity_subject_kind: { type: 'string', enum: ['agent', 'service', 'workload', 'user', 'composite', 'delegated-agent', 'unknown'], nullable: true },
      identity_subject_principal: { type: 'string', nullable: true },
      identity_trust_level: { type: 'string', enum: ['untrusted', 'restricted', 'supervised', 'autonomous'], nullable: true },
      identity_delegation_mode: { type: 'string', enum: ['none', 'on-behalf-of', 'impersonation'], nullable: true },
      identity: { type: 'string', nullable: true, description: 'JSON blob: full identity declaration' },

      // v0.2 Authorization Proof
      authorization_proof_ref: { type: 'string', nullable: true },
      authorization_proof: { type: 'string', nullable: true, description: 'JSON blob: authorization proof structure' },

      // v0.2 Authorization
      authorization_ref: { type: 'string', nullable: true },
      authorization: { type: 'string', nullable: true, description: 'JSON blob: authorization policy declaration' },

      // v0.2 Evidence
      evidence_ref: { type: 'string', nullable: true },
      evidence: { type: 'string', nullable: true, description: 'JSON blob: evidence collection declaration' },

      // v0.2 Contract
      contract_required_trust_level: { type: 'string', enum: ['untrusted', 'restricted', 'supervised', 'autonomous'], nullable: true },
      contract_trust_enforcement: { type: 'string', enum: ['none', 'warn', 'block', 'advisory', 'strict'], nullable: true, description: 'advisory/strict normalize to warn/block at runtime' },
      contract_sandbox: { type: 'string', nullable: true, description: 'JSON blob: sandbox constraints' },
      contract_allowed_paths: { type: 'string', nullable: true, description: 'JSON blob: allowed filesystem paths' },
      contract_network: { type: 'string', nullable: true, description: 'JSON blob: network access policy' },
      contract_max_cost_usd: { type: 'number', nullable: true, min: 0 },
      contract_audit: { type: 'string', nullable: true, description: 'JSON blob: audit configuration' },
      child_credential_policy: { type: 'string', nullable: true, enum: ['none', 'inherit', 'downscope', 'independent'], description: 'Credential flow policy for child tasks' },
    },
  },
  runs: {
    statuses: ['pending', 'running', 'ok', 'error', 'timeout', 'skipped', 'awaiting_approval', 'approved', 'cancelled', 'crashed'],
    key_fields: ['job_id', 'status', 'started_at', 'finished_at', 'summary', 'error_message', 'shell_exit_code', 'shell_signal', 'shell_timed_out', 'shell_stdout', 'shell_stderr', 'shell_stdout_path', 'shell_stderr_path', 'shell_stdout_bytes', 'shell_stderr_bytes', 'retry_of', 'triggered_by_run', 'dispatch_queue_id', 'idempotency_key', 'identity_resolved', 'trust_evaluation', 'authorization_decision', 'authorization_proof_verification', 'evidence_record', 'credential_handoff_summary'],
  },
  approvals: {
    statuses: ['pending', 'approved', 'rejected', 'timed_out', 'dispatched'],
    key_fields: ['job_id', 'run_id', 'dispatch_queue_id', 'requested_at', 'resolved_at', 'resolved_by', 'notes'],
  },
  dispatches: {
    kinds: ['manual', 'chain', 'retry'],
    statuses: ['pending', 'claimed', 'awaiting_approval', 'done', 'cancelled'],
    key_fields: ['job_id', 'dispatch_kind', 'status', 'scheduled_for', 'source_run_id', 'retry_of_run_id'],
  },
  messages: {
    kinds: ['text', 'task', 'result', 'status', 'system', 'spawn', 'decision', 'constraint', 'fact', 'preference'],
    statuses: ['pending', 'delivered', 'read', 'expired', 'failed'],
  },
};
